# [START app_yaml]
runtime: nodejs14
env_variables:
  FIREBASE_KEY: $FIREBASE_KEY
  WF_API_KEY: $WF_API_KEY
  WF_CHAMPS_ID: $WF_CHAMPS_ID
  WF_MATCHES_ID: $WF_MATCHES_ID
  WF_ROUNDS_ID: $WF_ROUNDS_ID
  WF_SITE_ID: $WF_SITE_ID
  WF_STORIES_ID: $WF_STORIES_ID
  API_VERSION: "v1"
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
    http_headers:
      Access-Control-Allow-Origin:
        - https://app.purplewallstories.com
        - https://dev.purplewallstories.com
        - https://www.purplewallstories.com
        - https://purplewallstories.com
        - https://purple-wall.webflow.io
# [END app_yaml]
