# [START app_yaml]
runtime: nodejs16

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

env_variables:
  FIREBASE_KEY: $FIREBASE_KEY
  WF_API_KEY: $WF_API_KEY
  WF_CHAMPS_ID: $WF_CHAMPS_ID
  WF_MATCHES_ID: $WF_MATCHES_ID
  WF_ROUNDS_ID: $WF_ROUNDS_ID
  WF_SITE_ID: $WF_SITE_ID
  WF_STORIES_ID: $WF_STORIES_ID
  API_VERSION: "v1"
# [END app_yaml]
