# [START app_yaml]
runtime: nodejs14
env_variables:
  FIREBASE_KEY: $FIREBASE_KEY
  WF_API_KEY: $WF_API_KEY
  WF_CHAMPS_ID: $WF_CHAMPS_ID
  WF_MATCHES_ID: $WF_MATCHES_ID
  WF_ROUNDS_ID: $WF_ROUNDS_ID
  WF_SITE_ID: $WF_SITE_ID
  WF_STORIES_ID: $WF_STORIES_ID

handlers:
  - url: /.*
    secure: always
    http_headers:
      Access-Control-Allow-Origin: [
          'https://app.purplewallstories.com',
          'https://dev.purplewallstories.com',
          'https://purple-wall.appspot.com',
          'https://purple-wall.webflow.io',
          'https://*.purplewallstories.com',
      ]
    script: auto
# [END app_yaml]
